version: '3.8'

services:
  db:
    image: postgres:11
    container_name: ezops-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql
    ports:
      - "5432:5432"
    networks:
      - ezops-net

  api:
    build: .
    container_name: ezops-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    networks:
      - ezops-net

volumes:
  pgdata:

networks:
  ezops-net:
